### ISSUE TITLE
Unable to update records, Webapp crashes

### ISSUE THREAD

**Issue by pschulz1** [hashicorp/field-workshops-vault#30]
It seems there is an issue when updating records. 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

On the "Vault CLI" where the python app is started:

In Main...
2020-04-03 08:31:58,606 -     INFO -       app -        <module> - Vault is enabled...
2020-04-03 08:31:58,607 -  WARNING - db_client -      init_vault - Connecting to vault server: http://localhost:8200
2020-04-03 08:31:58,614 -     INFO -       app -        <module> - using dynamic credentials from Vault: v-token-workshop-a-etTsah3hTPDzp with password A1a-ej01uMi4QBEFjEGA
2020-04-03 08:31:58,680 -     INFO - db_client -         init_db - Preparing database my_app...
2020-04-03 08:31:58,680 -     INFO - db_client -         init_db - Preparing customer table...
2020-04-03 08:31:58,681 -     INFO -       app -        <module> - Starting Flask server on 0.0.0.0 listening on port 5000
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-04-03 08:31:58,682 -    ERROR -      root -        <module> - There was an error starting the server: [Errno 98] Address already in use
2020-04-03 08:32:04,110 -     INFO -  werkzeug -            _log - 10.96.16.130 - - [03/Apr/2020 08:32:04] "GET / HTTP/1.1" 200 -
2020-04-03 08:32:05,321 -     INFO -  werkzeug -            _log - 10.96.16.130 - - [03/Apr/2020 08:32:05] "GET /update HTTP/1.1" 200 -
2020-04-03 08:32:16,745 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:16,746 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:16,746 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:16,746 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:16,747 -    ERROR -       app -   log_exception - Exception on /update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in update_submit
    records = update_customer()
  File "app.py", line 71, in update_customer
    new_record = dbc.update_customer_record(customer)
  File "/home/vault/transit-app-example/backend/db_client.py", line 218, in update_customer_record
    self._execute_sql(statement, cursor)
  File "/home/vault/transit-app-example/backend/db_client.py", line 118, in _execute_sql
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 590, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 478, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '['4']' at line 3
2020-04-03 08:32:16,749 -     INFO -  werkzeug -            _log - 10.96.47.112 - - [03/Apr/2020 08:32:16] "POST /update HTTP/1.1" 500 -
2020-04-03 08:32:17,807 -     INFO -  werkzeug -            _log - 10.96.46.46 - - [03/Apr/2020 08:32:17] "HEAD /update HTTP/1.1" 200 -
2020-04-03 08:32:17,844 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:17,844 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:17,845 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:17,845 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:17,845 -    ERROR -       app -   log_exception - Exception on /update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in update_submit
    records = update_customer()
  File "app.py", line 71, in update_customer
    new_record = dbc.update_customer_record(customer)
  File "/home/vault/transit-app-example/backend/db_client.py", line 218, in update_customer_record
    self._execute_sql(statement, cursor)
  File "/home/vault/transit-app-example/backend/db_client.py", line 118, in _execute_sql
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 590, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 478, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '['4']' at line 3
2020-04-03 08:32:17,848 -     INFO -  werkzeug -            _log - 10.96.46.46 - - [03/Apr/2020 08:32:17] "POST /update HTTP/1.1" 500 -
2020-04-03 08:32:18,911 -     INFO -  werkzeug -            _log - 10.96.45.246 - - [03/Apr/2020 08:32:18] "HEAD /update HTTP/1.1" 200 -
2020-04-03 08:32:18,952 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:18,953 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:18,953 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:18,953 -    ERROR - db_client -         encrypt - There was an error encrypting the data: 'list' object has no attribute 'encode'
2020-04-03 08:32:18,954 -    ERROR -       app -   log_exception - Exception on /update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in update_submit
    records = update_customer()
  File "app.py", line 71, in update_customer
    new_record = dbc.update_customer_record(customer)
  File "/home/vault/transit-app-example/backend/db_client.py", line 218, in update_customer_record
    self._execute_sql(statement, cursor)
  File "/home/vault/transit-app-example/backend/db_client.py", line 118, in _execute_sql
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 590, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 478, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '['4']' at line 3
2020-04-03 08:32:18,956 -     INFO -  werkzeug -            _log - 10.96.16.130 - - [03/Apr/2020 08:32:18] "POST /update HTTP/1.1" 500 -

  File "app.py", line 71, in update_customer
    new_record = dbc.update_customer_record(customer)
  File "/home/vault/transit-app-example/backend/db_client.py", line 218, in update_customer_record
    self._execute_sql(statement, cursor)
  File "/home/vault/transit-app-example/backend/db_client.py", line 118, in _execute_sql
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 590, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.5/dist-packages/mysql/connector/connection.py", line 478, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '['4']' at line 3
2020-04-03 08:32:18,956 -     INFO -  werkzeug -            _log - 10.96.16.130 - - [03/Apr/2020 08:32:18] "POST /update HTTP/1.1" 500 -

[2]+  Done                    python3 app.py

**Comment by rberlind** [comment]
This is being fixed in https://github.com/hashicorp/field-workshops-vault/pull/39
